version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-config/postgresql.conf:/etc/postgresql/postgresql.conf   # Mount custom postgresql.conf
      - ./postgres-config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]  # Use custom config file
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  mariadbx:
    image: mariadb:latest
    container_name: mariadbx
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadbx-data:/var/lib/mysql
      - ./logs/mariadbx:/var/log/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  phpmyadminx:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadminx
    environment:
      PMA_HOST: mariadbx
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mariadbx
    volumes:
      - ./logs/phpmyadminx:/var/log/phpmyadmin
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  metabasex:
    image: metabase/metabase:latest
    container_name: metabasex
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabasex-data:/metabase-data
      - ./logs/metabasex:/var/log/metabase
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./logs/zookeeper:/var/log/zookeeper
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs/kafka:/var/log/kafka
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  connect:
    image: debezium/connect:latest
    container_name: connect
    ports:
      - "8083:8083"
    environment:
      CONFIG_STORAGE_TOPIC: debezium_connect_configs
      OFFSET_STORAGE_TOPIC: debezium_connect_offsets
      STATUS_STORAGE_TOPIC: debezium_connect_statuses
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      CLASSPATH: /usr/share/java/*:/connectors/*
    depends_on:
      - kafka
    volumes:
      - ./logs/connect:/var/log/connect
      - D:/new_kafka:/connectors
      - D:/new_kafka/props:/usr/share/java
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./logs/clickhouse:/var/log/clickhouse
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres-data:
  mariadbx-data:
  metabasex-data:
  clickhouse-data:
